version: "3.9"
services:
  db:
    image: mysql:8.0
    volumes:
      - db_vol:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
  api:
    build: ./backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - ./backend:/api
    ports:
      - "3001:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      EMAIL_ADDRESS: $EMAIL_ADDRESS
      EMAIL_PASSWORD: $EMAIL_PASSWORD
  front:
    build: ./frontend/
    command: sh -c "npm start"
    volumes:
      - ./frontend/app:/front
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  db_vol:
